export const properties = {
  aubade: {
    slug: 'aubade',
    photo: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1400&q=80&auto=format&fit=crop',
    heroPhoto: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=2000&q=85&auto=format&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1400&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=1200&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=1200&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1584738766473-61c083514bf4?w=1200&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=1200&q=80&auto=format&fit=crop',
    ],
    altPhoto1: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=1200&q=80&auto=format&fit=crop',
    altPhoto2: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=1200&q=80&auto=format&fit=crop',
  },
  jaulerry: {
    slug: 'jaulerry',
    photo: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=1400&q=80&auto=format&fit=crop',
    heroPhoto: 'https://images.unsplash.com/photo-1505873242700-f289a29e1e0f?w=2000&q=85&auto=format&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1505873242700-f289a29e1e0f?w=1400&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1200&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1200&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=1200&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=1200&q=80&auto=format&fit=crop',
    ],
    altPhoto1: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1200&q=80&auto=format&fit=crop',
    altPhoto2: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1200&q=80&auto=format&fit=crop',
  },
  iena: {
    slug: 'iena',
    photo: 'https://images.unsplash.com/photo-1565182999561-18d7dc61c393?w=1400&q=80&auto=format&fit=crop',
    heroPhoto: 'https://images.unsplash.com/photo-1600210492493-0946911123ea?w=2000&q=85&auto=format&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1600210492493-0946911123ea?w=1400&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=1200&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=1200&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=1200&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=1200&q=80&auto=format&fit=crop',
    ],
    altPhoto1: 'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=1200&q=80&auto=format&fit=crop',
    altPhoto2: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=1200&q=80&auto=format&fit=crop',
  },
}

export const content = {
  fr: {
    nav: {
      maisons: 'Nos maisons',
      aubade: "L'Aubade",
      jaulerry: 'Jaulerry',
      iena: 'Iéna',
      contact: 'Contact',
    },
    home: {
      tagline: 'Des maisons habitées, jamais mises en scène.',
      subtagline: 'Homes that are lived in, never staged.',
      heroCta: 'Découvrir nos maisons',
      brandEyebrow: 'La marque',
      brandTitle: 'Les Maisons de Marguerite',
      brandP1: "Les Maisons de Marguerite est née d'une idée simple : partager les maisons que l'on aime.",
      brandP2: "Le nom rend hommage à la grand-mère de Val, qui a construit L'Aubade avec son mari. C'est un clin d'œil discret à l'histoire familiale.",
      brandP3: "Ce qui compte, c'est le regard de Val sur chaque espace : le choix des matières, l'attention au détail, ce sens du chez-soi qu'elle insuffle dans chaque maison.",
      propertiesEyebrow: 'Nos trois maisons',
      propertiesTitle: "Trois adresses, trois manières d'habiter la France",
      cardCta: 'Découvrir',
      contactEyebrow: 'Écrire à Val',
      contactTitle: 'Une question ? Écrivez à Val.',
      contactSubtitle: 'Val répond à chaque demande dans les 48 heures ouvrables.',
      firstName: 'Prénom',
      email: 'Email',
      message: 'Message',
      property: 'Bien concerné',
      propertyChoose: 'Choisir une maison…',
      propertyOther: 'Autre demande',
      send: 'Envoyer',
      thanksTitle: 'Message envoyé.',
      thanksText: 'Val vous répond dans les 48 heures ouvrables.',
    },
    cards: {
      aubade: {
        title: "L'Aubade",
        location: 'Périgord Vert, Dordogne',
        info: ['4 suites · 8 personnes', 'Location saisonnière'],
        price: '450 €',
        priceUnit: '/ nuit (mai → octobre)',
      },
      jaulerry: {
        title: 'Jaulerry',
        location: 'Biarritz, Pays Basque',
        info: ['3 chambres · 6 personnes', 'Bail mobilité'],
        price: '2 800 €',
        priceUnit: '/ mois · parking option',
      },
      iena: {
        title: 'Iéna',
        location: 'Paris 16ᵉ',
        info: ['2 chambres · 4 personnes', 'Bail mobilité'],
        price: '6 000 €',
        priceUnit: '/ mois · parking inclus',
      },
    },
    aubade: {
      title: "L'Aubade",
      heroTagline: "L'Aubade a été construite, vécue, transformée. Val l'a repensée à son image — les matières, les volumes, chaque détail choisi.",
      keyInfo: [
        ['Lieu', 'Saint-Aquilin, Dordogne — Périgord Vert'],
        ['Type', 'Maison de famille rénovée · 380 m²'],
        ['Capacité', '8 personnes · 4 suites'],
        ['Tarif', '450 € / nuit (mai → octobre), à la semaine'],
        ['Accès', '20 min Périgueux · 1 h 10 Bordeaux'],
      ],
      lede: 'Une maison de pierre dans le Périgord, repensée pour les longues semaines d\'été.',
      infos: [
        { icon: 'Waves', label: 'Piscine', value: 'Chauffée juin → août' },
        { icon: 'BedDouble', label: 'Couchages', value: '4 suites · master 60 m²' },
        { icon: 'Flame', label: 'Extérieur', value: 'BBQ Weber gaz · plancha' },
        { icon: 'Wifi', label: 'Connexion', value: 'WiFi terrasses & chambres' },
        { icon: 'KeyRound', label: 'Arrivée', value: 'Accès autonome (boîte à clé)' },
        { icon: 'Mountain', label: 'Vue', value: 'Sur la vallée et le parc' },
      ],
      descTitle: 'La maison',
      descP1: "L'Aubade a été construite, agrandie, soignée pendant des décennies. Val l'a repensée dans ses volumes et son confort. La grange rénovée, les pierres apparentes, les poutres anciennes : tout est là, intact. L'espace de vie de 100 m² est résolument contemporain, mais les matières restent celles du Périgord.",
      descP2: "Quatre suites, dont une master de 60 m², deux chambres climatisées, des terrasses avec vue sur la vallée et le parc. Une piscine chauffée de juin à août. Bruno entretient le jardin et la piscine deux fois par semaine, le matin.",
      equipTitle: 'Tous les équipements',
      equip: [
        'Piscine chauffée juin → août',
        'Piscine non chauffée mai, sept., oct.',
        '4 suites dont master 60 m²',
        '2 chambres climatisées',
        'Sonos 3 enceintes (salon, cheminée, piscine, master)',
        'BBQ Weber gaz',
        'Plancha',
        'Brasero',
        'Molky, pétanque',
        'Cheminée Focus',
        'WiFi terrasses & chambres',
        'Accès autonome (boîte à clé)',
      ],
      faqTitle: 'Bon à savoir',
      faq: [
        ["Quelle est la durée minimale de séjour à L'Aubade ?", "L'Aubade se loue à la semaine, de mai à octobre. Nous acceptons ponctuellement des séjours de 4 nuits minimum en début et fin de saison."],
        ['La piscine est-elle chauffée ?', 'Oui, la piscine est chauffée de juin à août. En mai, septembre et octobre, elle reste disponible mais sans chauffage.'],
        ["L'Aubade est-elle adaptée aux familles avec enfants ?", "Tout à fait. La maison accueille jusqu'à 8 personnes, avec 4 suites indépendantes. L'alarme piscine est conforme à la loi. Le jardin est clos."],
        ["Comment se passe l'arrivée ?", "L'accès est autonome via une boîte à clé sécurisée. Les codes et instructions sont envoyés avant votre arrivée. Un guide complet est disponible en ligne."],
        ['Quelles activités sont disponibles à proximité ?', "L'Aubade est à 20 minutes de Périgueux et 1 h 10 de Bordeaux. À proximité : marché de Saint-Astier, canoë sur la Dronne, châteaux et grottes du Périgord."],
        ["Quel est le tarif pour L'Aubade ?", "450 € par nuit, de mai à octobre. Location à la semaine. Pour toute demande hors saison, contactez Val via le formulaire."],
      ],
      ctaTitle: "Envie de réserver L'Aubade ?",
      ctaText: 'Val répond à chaque demande dans les 48 heures ouvrables.',
      ctaBtn: 'Contacter Val',
      guideLinkLede: 'Vous avez une réservation ?',
      guideLinkText: "Accédez à votre guide d'arrivée.",
    },
    jaulerry: {
      title: 'Jaulerry',
      heroTagline: 'Un appartement de caractère à deux pas des Halles. Vivre Biarritz, vraiment, sans chercher sa voiture le matin.',
      keyInfo: [
        ['Lieu', 'Biarritz, Pays Basque'],
        ['Type', "Appartement 200 m² · 1ᵉʳ étage, immeuble années 30"],
        ['Capacité', '6 personnes · 3 chambres · 3 SDB privées'],
        ['Tarif', '2 800 € / mois — bail mobilité'],
        ['Parking', '80 € / mois (parking de la Poste, 5 min)'],
        ['Accès', '5 min Grande Plage · 200 m Halles'],
      ],
      lede: 'Tout un étage des années 30, à deux pas des Halles et de la Grande Plage.',
      infos: [
        { icon: 'Wifi', label: 'Connexion', value: 'WiFi 389 Mbit/s' },
        { icon: 'Monitor', label: 'Travail', value: 'Espace de travail dédié' },
        { icon: 'Car', label: 'Parking', value: 'Option · 80 € / mois' },
        { icon: 'Bath', label: 'Salles de bain', value: '3 SDB privées' },
        { icon: 'Flame', label: 'Salon', value: 'Double séjour avec cheminée' },
        { icon: 'MapPin', label: 'Plage', value: '5 min Grande Plage' },
      ],
      descTitle: "L'appartement",
      descP1: "Jaulerry occupe tout le premier étage d'un bel immeuble des années 30, en plein cœur de Biarritz. 200 m² sur un seul niveau, trois chambres avec salle de bain privée, un double séjour avec cheminée qui donne directement sur les Halles.",
      descP2: "La Grande Plage est à 5 minutes à pied. Le marché des Halles, à 200 mètres. La connexion WiFi atteint 389 Mbit/s et l'espace de travail dédié est séparé des chambres. On ne prend la voiture que si on le décide.",
      faqTitle: 'Bon à savoir',
      faq: [
        ["Qu'est-ce qu'un bail mobilité et à qui s'adresse-t-il ?", "Le bail mobilité est un contrat de location meublée de 1 à 10 mois, réservé aux personnes en formation, mission professionnelle, études ou mutation. Il n'est pas renouvelable mais offre une grande souplesse."],
        ["Le parking est-il inclus dans le loyer ?", "Le parking n'est pas inclus dans le loyer de base. Une carte d'accès au parking de La Poste, à 5 minutes à pied, est disponible en option pour 80 € / mois."],
        ["L'appartement est-il adapté au télétravail ?", "Oui. Jaulerry dispose d'une connexion WiFi rapide (389 Mbit/s) et d'un espace de travail dédié. Les 3 chambres sont au calme, sur cour."],
        ["Quel est le délai de réponse après une demande de contact ?", 'Val répond à chaque demande dans les 48 heures ouvrables.'],
        ['Quel est le tarif mensuel pour Jaulerry ?', '2 800 € par mois en bail mobilité. Parking disponible en option pour 80 € par mois supplémentaires.'],
      ],
      ctaTitle: 'Envie de venir vivre à Jaulerry ?',
      ctaText: 'Val répond à chaque demande dans les 48 heures ouvrables.',
      ctaBtn: 'Contacter Val',
    },
    iena: {
      title: 'Iéna',
      heroTagline: "Iéna est calme. C'est la première chose qu'on remarque en entrant, pour un appartement entre la Tour Eiffel et les Champs-Élysées.",
      keyInfo: [
        ['Lieu', 'Paris 16ᵉ — entre Tour Eiffel et Champs-Élysées'],
        ['Type', "Duplex 125 m² · ancien hôtel particulier"],
        ['Capacité', '4 personnes · 2 chambres · 2 SDB privées'],
        ['Tarif', '6 000 € / mois — bail mobilité'],
        ['Parking', 'Inclus · garage anciennes écuries, cour intérieure'],
      ],
      lede: 'Un duplex haussmannien donnant sur une cour intérieure arborée. Le silence comme luxe premier.',
      infos: [
        { icon: 'Car', label: 'Parking', value: "Inclus · anciennes écuries" },
        { icon: 'Trees', label: 'Cour', value: 'Cour intérieure arborée' },
        { icon: 'Monitor', label: 'Travail', value: 'Espace mezzanine' },
        { icon: 'Bath', label: 'Salles de bain', value: '2 SDB privées' },
        { icon: 'Layers', label: 'Immeuble', value: 'Ascenseur' },
        { icon: 'Thermometer', label: 'Confort', value: 'Chauffage central' },
      ],
      descTitle: 'Le duplex',
      descP1: "Iéna est calme. C'est la première chose qu'on remarque en entrant. L'appartement donne sur une cour intérieure arborée : on ne s'y attend pas, dans ce quartier. Le duplex de 125 m² a été entièrement rénové en conservant le caractère haussmannien : hauteur sous plafond, moulures, parquet. La cuisine est ultra-contemporaine. Les salles de bain aussi. Les deux mondes cohabitent sans effort.",
      descP2: "Au premier niveau, un salon cathédrale traversé par la lumière de deux immenses fenêtres. À l'étage, un espace de travail sur mezzanine, la chambre principale de 23 m² avec douche italienne, et une seconde chambre avec sa propre salle de bain. Un garage dans les anciennes écuries est inclus dans le loyer.",
      faqTitle: 'Bon à savoir',
      faq: [
        ["Qu'est-ce qu'un bail mobilité et à qui s'adresse-t-il ?", "Le bail mobilité est un contrat de location meublée de 1 à 10 mois, réservé aux personnes en formation, mission professionnelle, études ou mutation. Il offre une grande souplesse sans reconduction tacite."],
        ['Le parking est-il inclus ?', "Oui. Un garage dans les anciennes écuries de l'immeuble est inclus dans le loyer, accessible depuis la cour intérieure avec un badge."],
        ["L'appartement est-il calme malgré sa situation centrale ?", "Oui. Iéna donne sur une cour intérieure arborée, à l'abri de la rue. C'est l'une de ses caractéristiques les plus appréciées."],
        ["L'appartement est-il adapté à une mission professionnelle longue durée ?", "C'est précisément pour cela qu'il a été pensé. Espace de travail sur mezzanine, WiFi haut débit, deux chambres indépendantes, parking inclus. Entre la Tour Eiffel et les Champs-Élysées."],
        ['Quel est le tarif mensuel pour Iéna ?', '6 000 € par mois en bail mobilité, parking inclus.'],
      ],
      ctaTitle: 'Envie de venir vivre à Iéna ?',
      ctaText: 'Val répond à chaque demande dans les 48 heures ouvrables.',
      ctaBtn: 'Contacter Val',
    },
    guide: {
      stayLabel: "Guide d'arrivée — L'Aubade",
      title: "Le Guide de L'Aubade",
      intro: 'La maison vous attend. Tout est préparé pour que vous preniez vos marques sans chercher, sans appeler, sans attendre.',
      tiles: [
        { id: 'arrivee', icon: 'MapPin', title: 'Arrivée', desc: "Adresse, accès, boîte à clé, contacts", photo: 'https://images.unsplash.com/photo-1518780664697-55e3ad937233?w=1200&q=80&auto=format&fit=crop' },
        { id: 'maison', icon: 'Home', title: 'La Maison', desc: 'WiFi, Sonos, piscine, BBQ, cheminée', photo: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=1200&q=80&auto=format&fit=crop' },
        { id: 'carnet', icon: 'BookOpen', title: 'Le Carnet de Val', desc: 'Tables, marchés, producteurs, secrets locaux', photo: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=1200&q=80&auto=format&fit=crop' },
        { id: 'depart', icon: 'CheckSquare', title: 'Le Départ', desc: 'Checklist, clés, mot de Val', photo: 'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=1200&q=80&auto=format&fit=crop' },
      ],
    },
    guideArrivee: {
      title: 'Arrivée',
      intro: 'La maison vous attend. Tout est préparé pour que vous preniez vos marques sans chercher, sans appeler, sans attendre.',
      addressLabel: 'Adresse',
      address: '540 Voie Romaine, 24110 Saint-Aquilin',
      gps: '45.19812, 0.48011',
      access: 'Prendre le chemin sur la droite, portail 100 m plus haut.',
      keyLabel: 'Boîte à clé',
      keyDetails: 'Poteau gauche face au portail. Code envoyé par WhatsApp 24 h avant l\'arrivée.',
      hoursLabel: 'Horaires',
      hours: 'Arrivée à partir de 14 h · départ au plus tard 12 h',
      teamTitle: "L'équipe sur place",
      team: [
        ['Bruno', 'Jardin et piscine — mardi et jeudi avant 10 h'],
        ['Joëlle', 'Ménage entre séjours — contacter via Val'],
      ],
      emergencyTitle: 'Numéros utiles',
      emergency: [
        ['SAMU', '15'],
        ['Pompiers', '18'],
        ['Gendarmerie', '17'],
        ['Hôpital Périgueux', '+33 5 53 45 25 25'],
        ['Pharmacie Saint-Astier', '+33 5 53 54 11 26'],
      ],
    },
    guideMaison: {
      title: 'La Maison',
      intro: 'Tout ce qu\'il faut savoir pour vous sentir chez vous dès la première heure.',
      wifiNetwork: 'Aubade-Guest',
      wifiPassword: 'ensemble2024',
      sonosText: 'Spotify, Deezer ou Apple Music. 4 zones : salon, coin cheminée, piscine, master bedroom.',
      poolText: 'Chauffage automatique 24 °C, rien à allumer ni éteindre. Désactiver l\'alarme avant de nager — elle se réenclenche automatiquement.',
      bbqText: 'Gaz fourni · bouteille supplémentaire côté cave à vin. Merci de passer un coup sur la grille après chaque usage.',
      fireplaceSteps: [
        "Ouvrir la trappe avant d'allumer.",
        'Allumer le feu (bois fourni à côté).',
        'Fermer la trappe une fois le feu éteint.',
      ],
      misc: [
        ['Poubelles', 'Containers tri sélectif sur la route, 200 m à droite en sortant.'],
        ['Tableau électrique', 'Derrière la cave à vin.'],
      ],
    },
    guideCarnet: {
      title: 'Le Carnet de Val',
      intro: 'Les adresses que Val partage, dans l\'ordre où elle les conseillerait à un ami qui vient passer la semaine.',
      groups: [
        {
          eyebrow: 'La table',
          items: [
            { name: 'Le Singulier', meta: 'Saint-Astier · 15 min', quote: 'Ma table de référence. On y mange bien, sans chichi, avec de vrais produits du coin.' },
            { name: 'Le Restaurant du Caviar de Neuvic', meta: 'Neuvic · 10 min', quote: 'Pour une occasion. Le cadre au bord de l\'eau, le caviar produit sur place.' },
          ],
        },
        {
          eyebrow: 'Le marché',
          items: [
            { name: 'Marché de Saint-Astier', meta: 'Jeudi matin · 15 min', quote: 'Le marché de la semaine. On y va les mains vides et on rentre chargé.' },
            { name: 'Marché de Périgueux', meta: 'Mercredi & samedi matin · 20 min', quote: 'Pour l\'ambiance et les halles couvertes. Le samedi c\'est le bon jour.' },
          ],
        },
        {
          eyebrow: 'Les producteurs',
          items: [
            { name: 'Boulangerie Barreca', meta: 'Neuvic · 10 min', quote: 'Le pain du séjour.' },
            { name: 'La Boucherie Neuvicoise', meta: 'Neuvic · 10 min', quote: 'Pour la viande, avant le BBQ du soir.' },
            { name: 'La Ferme de Marcel', meta: 'Saint-Aquilin · 5 min', quote: 'À deux pas. On va chercher directement à la ferme.' },
            { name: 'Chai Arnaud', meta: 'Saint-Astier · 15 min', quote: 'Pour choisir une bonne bouteille avant de rentrer.' },
          ],
        },
        {
          eyebrow: 'À faire',
          items: [
            { name: 'Brantôme', meta: '30 min', quote: 'La Venise du Périgord. On a envie de rester.' },
            { name: 'Canoë sur la Dronne', meta: 'Saint-Astier ou Brantôme', quote: 'Pour une demi-journée sur l\'eau.' },
            { name: 'Distillerie de l\'Ort', meta: '40 min', quote: 'Gin, vermouth, pastis du Périgord.' },
            { name: "Écomusée de la Truffe", meta: 'Sorges · 25 min', quote: 'La visite est vraiment bien faite.' },
          ],
        },
      ],
    },
    guideDepart: {
      title: 'Le Départ',
      intro: 'La maison vous a bien reçus. Voici ce qu\'on vous demande avant de partir.',
      hours: 'Heure de départ : au plus tard 12 h.',
      checklist: [
        'Vaisselle faite et rangée',
        'Frigo vidé',
        'Poubelles sorties (containers à 200 m à droite)',
        'Draps et serviettes rassemblés dans la buanderie',
        'Fenêtres fermées',
        'Volets fermés',
        'Portail fermé',
      ],
      keysText: 'Déposer la clé et le badge dans la boîte à clé. Même code qu\'à l\'arrivée.',
      wordText: "Merci d'avoir pris soin de L'Aubade. J'espère que vous avez pris le temps de profiter. Si quelque chose n'allait pas, un message WhatsApp suffit. À bientôt, j'espère.",
      signature: '— Val',
    },
    common: {
      back: 'Retour',
      backHome: 'Accueil',
      learnMore: 'Découvrir',
      bookGuide: 'Vous avez une réservation ?',
      bookGuideCta: 'Accéder à votre guide',
    },
    footer: {
      promise: "Trois adresses choisies, trois manières d'habiter la France. Un seul regard : celui de Val.",
      explore: 'Explorer',
      practical: 'Pratique',
      newsletter: 'La lettre de Val',
      newsletterText: "Une lettre tous les trois mois, signée Val. Les nouvelles des maisons, les adresses qu'elle aime.",
      newsletterCta: 'Recevoir la lettre',
      placeholder: 'Votre email',
      legal: 'Mentions légales',
      privacy: 'Confidentialité',
      contact: 'Contact',
      instagram: 'Instagram',
      copy: '© 2026 Les Maisons de Marguerite — Tous droits réservés.',
    },
  },

  en: {
    nav: {
      maisons: 'Our houses',
      aubade: "L'Aubade",
      jaulerry: 'Jaulerry',
      iena: 'Iéna',
      contact: 'Contact',
    },
    home: {
      tagline: 'Homes that are lived in, never staged.',
      subtagline: 'Des maisons habitées, jamais mises en scène.',
      heroCta: 'Discover our houses',
      brandEyebrow: 'The brand',
      brandTitle: 'Les Maisons de Marguerite',
      brandP1: 'Les Maisons de Marguerite was born from a simple idea: to share the homes we love.',
      brandP2: "The name pays tribute to Val's grandmother, who built L'Aubade with her husband. A quiet nod to a family story.",
      brandP3: "What matters is Val's eye on each space: the choice of materials, the attention to detail, the sense of home she brings to every house.",
      propertiesEyebrow: 'Three houses',
      propertiesTitle: 'Three addresses, three ways to inhabit France',
      cardCta: 'Discover',
      contactEyebrow: 'Write to Val',
      contactTitle: 'A question? Write to Val.',
      contactSubtitle: 'Val answers every enquiry within 48 working hours.',
      firstName: 'First name',
      email: 'Email',
      message: 'Message',
      property: 'House',
      propertyChoose: 'Choose a house…',
      propertyOther: 'Other enquiry',
      send: 'Send',
      thanksTitle: 'Message sent.',
      thanksText: 'Val will reply within 48 working hours.',
    },
    cards: {
      aubade: {
        title: "L'Aubade",
        location: 'Périgord Vert, Dordogne',
        info: ['4 suites · sleeps 8', 'Seasonal rental'],
        price: '€450',
        priceUnit: '/ night (May → October)',
      },
      jaulerry: {
        title: 'Jaulerry',
        location: 'Biarritz, Basque Country',
        info: ['3 bedrooms · sleeps 6', 'Mobility lease'],
        price: '€2,800',
        priceUnit: '/ month · parking optional',
      },
      iena: {
        title: 'Iéna',
        location: 'Paris 16th',
        info: ['2 bedrooms · sleeps 4', 'Mobility lease'],
        price: '€6,000',
        priceUnit: '/ month · parking included',
      },
    },
    aubade: {
      title: "L'Aubade",
      heroTagline: "Built, transformed, cared for. Val reimagined every detail. You feel it the moment you walk in.",
      keyInfo: [
        ['Location', 'Saint-Aquilin, Dordogne — Périgord Vert'],
        ['Type', 'Renovated family home · 380 m²'],
        ['Capacity', 'Sleeps 8 · 4 suites'],
        ['Price', '€450 / night (May → October), weekly stays'],
        ['Access', '20 min Périgueux · 1 h 10 Bordeaux'],
      ],
      lede: 'A stone house in the Périgord, reimagined for long summer weeks.',
      infos: [
        { icon: 'Waves', label: 'Pool', value: 'Heated June → August' },
        { icon: 'BedDouble', label: 'Sleeping', value: '4 suites · 60 m² master' },
        { icon: 'Flame', label: 'Outdoor', value: 'Weber gas BBQ · plancha' },
        { icon: 'Wifi', label: 'Connection', value: 'WiFi terraces & bedrooms' },
        { icon: 'KeyRound', label: 'Arrival', value: 'Self check-in (key box)' },
        { icon: 'Mountain', label: 'View', value: 'Valley and grounds' },
      ],
      descTitle: 'The house',
      descP1: "L'Aubade has been built, extended, and cared for over decades. Val reimagined its space and comfort. The renovated barn, the exposed stone, the old beams: all of it still there, untouched. The 100 m² living area is resolutely contemporary, but the materials remain those of the Périgord.",
      descP2: 'Four suites, including a 60 m² master suite, two air-conditioned bedrooms, terraces overlooking the valley and park. A heated pool from June to August.',
      equipTitle: 'Full amenities',
      equip: [
        'Heated pool June → August',
        'Unheated pool May, Sept, Oct',
        '4 suites incl. 60 m² master',
        '2 air-conditioned bedrooms',
        'Sonos · 3 speakers (living, fireplace, pool, master)',
        'Weber gas BBQ',
        'Plancha',
        'Brazier',
        'Mölkky, pétanque',
        'Focus fireplace',
        'WiFi terraces & bedrooms',
        'Self check-in (key box)',
      ],
      faqTitle: 'Good to know',
      faq: [
        ["What is the minimum stay at L'Aubade?", "L'Aubade is rented by the week, from May to October. We occasionally accept stays of 4 nights minimum at the start and end of the season."],
        ['Is the pool heated?', 'Yes, the pool is heated from June to August. In May, September and October, it remains available but unheated.'],
        ["Is L'Aubade suitable for families with children?", 'Absolutely. The house sleeps up to 8 across 4 independent suites. The pool alarm is compliant with French law. The garden is enclosed.'],
        ['How does arrival work?', 'Check-in is self-service via a secure key box. Codes and instructions are sent before your arrival. A full guide is available online.'],
        ['What is there to do nearby?', "L'Aubade is 20 minutes from Périgueux and 1 h 10 from Bordeaux. Nearby: Saint-Astier market, canoeing on the Dronne, the châteaux and caves of the Périgord."],
        ["What is the rate for L'Aubade?", '€450 per night, from May to October, weekly stays. For off-season enquiries, contact Val via the form.'],
      ],
      ctaTitle: "Thinking of booking L'Aubade?",
      ctaText: 'Val answers every enquiry within 48 working hours.',
      ctaBtn: 'Write to Val',
      guideLinkLede: 'Have a reservation?',
      guideLinkText: 'Access your arrival guide.',
    },
    jaulerry: {
      title: 'Jaulerry',
      heroTagline: 'A character apartment steps from Les Halles. Living in Biarritz, properly, without looking for your car every morning.',
      keyInfo: [
        ['Location', 'Biarritz, Basque Country'],
        ['Type', "200 m² apartment · 1st floor, 1930s building"],
        ['Capacity', 'Sleeps 6 · 3 bedrooms · 3 private bathrooms'],
        ['Price', '€2,800 / month — mobility lease'],
        ['Parking', 'Optional · €80 / month (Poste car park, 5 min)'],
        ['Access', '5 min Grande Plage · 200 m Halles market'],
      ],
      lede: "An entire 1930s floor, steps from Les Halles and the Grande Plage.",
      infos: [
        { icon: 'Wifi', label: 'Connection', value: 'WiFi 389 Mbit/s' },
        { icon: 'Monitor', label: 'Workspace', value: 'Dedicated study' },
        { icon: 'Car', label: 'Parking', value: 'Optional · €80 / month' },
        { icon: 'Bath', label: 'Bathrooms', value: '3 private' },
        { icon: 'Flame', label: 'Living', value: 'Double lounge with fireplace' },
        { icon: 'MapPin', label: 'Beach', value: '5 min Grande Plage' },
      ],
      descTitle: 'The apartment',
      descP1: "Jaulerry takes up the entire first floor of a handsome 1930s building in the heart of Biarritz. 200 m² on a single level, three bedrooms each with a private bathroom, a double living room with fireplace looking directly onto Les Halles.",
      descP2: "The Grande Plage is a 5-minute walk. The Halles market, 200 metres away. Fast WiFi (389 Mbit/s), a dedicated workspace. You take the car only when you choose to.",
      faqTitle: 'Good to know',
      faq: [
        ['What is a mobility lease and who is it for?', 'The French mobility lease is a furnished rental contract of 1 to 10 months, reserved for people in training, professional assignments, studies or relocation. It cannot be renewed but offers great flexibility.'],
        ['Is parking included in the rent?', "Parking is not included in the base rent. A key card for the Poste car park, 5 minutes' walk away, is available for €80 / month."],
        ['Is the apartment suited to remote work?', 'Yes. Jaulerry has a fast WiFi connection (389 Mbit/s) and a dedicated study. The 3 bedrooms are quiet, overlooking the courtyard.'],
        ['What is the response time after an enquiry?', 'Val answers every enquiry within 48 working hours.'],
        ['What is the monthly rate for Jaulerry?', '€2,800 per month under a mobility lease. Parking is available as an option for an additional €80 per month.'],
      ],
      ctaTitle: 'Thinking of moving to Jaulerry?',
      ctaText: 'Val answers every enquiry within 48 working hours.',
      ctaBtn: 'Write to Val',
    },
    iena: {
      title: 'Iéna',
      heroTagline: "Iéna is quiet. That's the first thing you notice — for an apartment between the Eiffel Tower and the Champs-Élysées.",
      keyInfo: [
        ['Location', 'Paris 16th — between Eiffel Tower and Champs-Élysées'],
        ['Type', "125 m² duplex · former hôtel particulier"],
        ['Capacity', 'Sleeps 4 · 2 bedrooms · 2 private bathrooms'],
        ['Price', '€6,000 / month — mobility lease'],
        ['Parking', 'Included · garage in former stables, inner courtyard'],
      ],
      lede: 'A Haussmann duplex onto a tree-lined inner courtyard. Silence as the first luxury.',
      infos: [
        { icon: 'Car', label: 'Parking', value: 'Included · former stables' },
        { icon: 'Trees', label: 'Courtyard', value: 'Tree-lined inner courtyard' },
        { icon: 'Monitor', label: 'Workspace', value: 'Mezzanine study' },
        { icon: 'Bath', label: 'Bathrooms', value: '2 private' },
        { icon: 'Layers', label: 'Building', value: 'Lift' },
        { icon: 'Thermometer', label: 'Comfort', value: 'Central heating' },
      ],
      descTitle: 'The duplex',
      descP1: "Iéna is quiet. That's the first thing you notice. The apartment faces a tree-lined internal courtyard: unexpected, in this neighbourhood. The 125 m² duplex has been fully renovated while keeping its Haussmann character: ceiling height, mouldings, parquet floors.",
      descP2: "On the first level, a double-height living room flooded with light. Upstairs, a mezzanine workspace, the 23 m² master bedroom with an Italian shower, and a second bedroom with its own bathroom. A garage in the building's former stables is included.",
      faqTitle: 'Good to know',
      faq: [
        ['What is a mobility lease and who is it for?', 'The mobility lease is a furnished rental contract of 1 to 10 months, reserved for people in training, professional assignments, studies or relocation.'],
        ['Is parking included?', "Yes. A garage in the building's former stables is included in the rent, accessed from the inner courtyard with a badge."],
        ['Is the apartment quiet despite its central location?', "Yes. Iéna faces a tree-lined inner courtyard, shielded from the street. It's one of its most appreciated features."],
        ['Is the apartment suited to a long professional assignment?', 'Mezzanine workspace, fast WiFi, two independent bedrooms, parking included. Between the Eiffel Tower and the Champs-Élysées.'],
        ['What is the monthly rate for Iéna?', '€6,000 per month under a mobility lease, parking included.'],
      ],
      ctaTitle: 'Thinking of moving to Iéna?',
      ctaText: 'Val answers every enquiry within 48 working hours.',
      ctaBtn: 'Write to Val',
    },
    guide: {
      title: "The L'Aubade Guide",
      intro: 'The house is waiting. Everything is ready so you can settle in without searching, calling, or waiting.',
      tiles: [
        { id: 'arrivee', icon: 'MapPin', title: 'Arrival', desc: 'Address, access, key box, contacts', photo: 'https://images.unsplash.com/photo-1518780664697-55e3ad937233?w=1200&q=80&auto=format&fit=crop' },
        { id: 'maison', icon: 'Home', title: 'The House', desc: 'WiFi, Sonos, pool, BBQ, fireplace', photo: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=1200&q=80&auto=format&fit=crop' },
        { id: 'carnet', icon: 'BookOpen', title: "Val's Notebook", desc: 'Tables, markets, makers, local secrets', photo: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=1200&q=80&auto=format&fit=crop' },
        { id: 'depart', icon: 'CheckSquare', title: 'Departure', desc: 'Checklist, keys, a note from Val', photo: 'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=1200&q=80&auto=format&fit=crop' },
      ],
    },
    guideArrivee: {
      title: 'Arrival',
      address: '540 Voie Romaine, 24110 Saint-Aquilin',
      gps: '45.19812, 0.48011',
      access: 'Take the path to the right; the gate is 100 m up.',
      keyDetails: 'Left post, facing the gate. Code sent via WhatsApp 24 h before arrival.',
      hours: 'Check-in from 2 pm · check-out by noon',
      team: [
        ['Bruno', 'Garden and pool — Tuesday and Thursday before 10 am'],
        ['Joëlle', 'Cleaning between stays — contact via Val'],
      ],
      emergency: [
        ['SAMU (medical)', '15'],
        ['Fire (Pompiers)', '18'],
        ['Police (Gendarmerie)', '17'],
        ['Périgueux hospital', '+33 5 53 45 25 25'],
        ['Saint-Astier pharmacy', '+33 5 53 54 11 26'],
      ],
    },
    guideMaison: {
      title: 'The House',
      wifiNetwork: 'Aubade-Guest',
      wifiPassword: 'ensemble2024',
      sonosText: 'Spotify, Deezer or Apple Music. 4 zones: living, fireplace nook, pool, master bedroom.',
      poolText: 'Automatic heating at 24 °C, nothing to switch on or off. Disable the alarm before swimming — it re-arms automatically.',
      bbqText: 'Gas provided; spare bottle by the wine cellar. Please give the grill a quick clean after each use.',
      fireplaceSteps: [
        'Open the flap before lighting.',
        'Light the fire (wood provided next to it).',
        'Close the flap once the fire is out.',
      ],
      misc: [
        ['Bins', 'Recycling containers on the road, 200 m to the right as you leave.'],
        ['Electrical panel', 'Behind the wine cellar.'],
      ],
    },
    guideCarnet: {
      title: "Val's Notebook",
      intro: "The addresses Val shares — in the order she'd suggest them to a friend spending the week.",
      groups: [
        {
          eyebrow: 'The table',
          items: [
            { name: 'Le Singulier', meta: 'Saint-Astier · 15 min', quote: 'My reference table. Honest cooking, real produce from nearby.' },
            { name: 'Le Restaurant du Caviar de Neuvic', meta: 'Neuvic · 10 min', quote: 'For an occasion. By the water, with caviar produced on site.' },
          ],
        },
        {
          eyebrow: 'The market',
          items: [
            { name: 'Saint-Astier market', meta: 'Thursday morning · 15 min', quote: 'You arrive empty-handed and leave loaded.' },
            { name: 'Périgueux market', meta: 'Wed. & Sat. morning · 20 min', quote: 'For the atmosphere and the covered halles. Saturday is the day.' },
          ],
        },
        {
          eyebrow: 'The makers',
          items: [
            { name: 'Boulangerie Barreca', meta: 'Neuvic · 10 min', quote: 'The bread of the stay.' },
            { name: 'La Boucherie Neuvicoise', meta: 'Neuvic · 10 min', quote: 'For the meat, before the evening BBQ.' },
            { name: 'La Ferme de Marcel', meta: 'Saint-Aquilin · 5 min', quote: 'Just down the road. Straight from the farm.' },
            { name: 'Chai Arnaud', meta: 'Saint-Astier · 15 min', quote: 'To choose a good bottle on the way home.' },
          ],
        },
        {
          eyebrow: 'To do',
          items: [
            { name: 'Brantôme', meta: '30 min', quote: 'The Venice of the Périgord. You want to stay.' },
            { name: 'Canoeing on the Dronne', meta: 'Saint-Astier or Brantôme', quote: 'For a half-day on the water.' },
            { name: "Distillerie de l'Ort", meta: '40 min', quote: 'Périgord gin, vermouth, pastis.' },
            { name: 'Truffle Ecomuseum', meta: 'Sorges · 25 min', quote: 'Genuinely well done.' },
          ],
        },
      ],
    },
    guideDepart: {
      title: 'Departure',
      hours: 'Check-out: by noon at the latest.',
      checklist: [
        'Dishes washed and put away',
        'Fridge emptied',
        'Bins taken out (containers 200 m to the right)',
        'Sheets and towels gathered in the laundry',
        'Windows closed',
        'Shutters closed',
        'Gate closed',
      ],
      keysText: 'Drop the key and badge in the key box. Same code as arrival.',
      wordText: "Thank you for taking care of L'Aubade. I hope you took the time to enjoy it. If anything wasn't right, a WhatsApp message is enough. See you soon, I hope.",
      signature: '— Val',
    },
    common: {
      back: 'Back',
      backHome: 'Home',
      learnMore: 'Discover',
      bookGuide: 'Have a reservation?',
      bookGuideCta: 'Open your guide',
    },
    footer: {
      promise: "Three chosen addresses, three ways to inhabit France. One eye behind them: Val's.",
      explore: 'Explore',
      practical: 'Practical',
      newsletter: "Val's letter",
      newsletterText: 'A letter every three months, from Val. News from the houses, the addresses she loves.',
      newsletterCta: 'Subscribe',
      placeholder: 'Your email',
      legal: 'Legal notice',
      privacy: 'Privacy',
      contact: 'Contact',
      instagram: 'Instagram',
      copy: '© 2026 Les Maisons de Marguerite — All rights reserved.',
    },
  },
}
